{% set name = "db-dtypes" %}
{% set version = "1.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d3cb08c32939d24e05501f17694be8c1c54cfb4620d61fb56fb311e8c3d8885e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - packaging >=24.2.0
    - pandas >=1.5.3
    - pyarrow >=13.0.0
    - numpy >=1.24.0

test:
  imports:
    - db_dtypes
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/googleapis/python-db-dtypes-pandas
  doc_url: https://googleapis.dev/python/db-dtypes/latest/index.html
  summary: Pandas Data Types for SQL systems (BigQuery, Spanner)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
    - tswast
